# Nombre del flujo de trabajo
name: Python Test Suite

# Este workflow se ejecuta automáticamente cuando se crea un pull request a la rama 'QA'
on:
  pull_request:
    branches:
      - qa # Se especifica que se activará cuando haya un pull request hacia la rama QA

jobs:
  # Nombre del job
  test:
    # Se ejecuta en un runner de Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Se clona el repositorio
      - name: Check out repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python en la versión especificada
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Paso 3: Instalar dependencias desde requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar las pruebas con pytest
      - name: Run Tests
        run: |
          pytest
        # El flujo de trabajo falla si alguna prueba falla
        continue-on-error: false
